Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: users-${self:provider.stage}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
