service: paloma
app: paloma
# org: DungBeetleBASH

# Serverless version
# Check out our docs for more details
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  region: eu-west-1
  profile: serverless-agent

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# environment variables
#  environment:
#    variable1: value1

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  users:
    handler: bin/users
    events:
      - http:
          path: users
          method: post
      - http:
          path: users
          method: put
      - http:
          path: users/{id}
          method: get
