Resources:
  PalomaDBCluster:
    Type: AWS::Neptune::DBCluster
  PalomaDBInstance:
    Type: AWS::Neptune::DBInstance
    Properties:
      DBInstanceClass: db.t3.medium
      DBClusterIdentifier: !Ref PalomaDBCluster

Outputs:
  PalomaDBCluster:
    Value:
      Ref: PalomaDBCluster
  PalomaDBInstance:
    Value:
      Ref: PalomaDBInstance
  PalomaDBClusterEndpointAddress:
    Value: !GetAtt PalomaDBCluster.Endpoint.Address
