service: paloma
app: paloma
# org: DungBeetleBASH

# Serverless version
# Check out our docs for more details
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  region: eu-west-1
  profile: serverless-agent
  environment:
    USERS_TABLE: "PalomaUsers${self:provider.stage}"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [UsersTable, Arn]

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  UsersPostConfirm:
    handler: bin/users/postConfirm
    events:
      - cognitoUserPool:
          pool: ${self:provider.stage}PalomaUserPool
          trigger: PostConfirmation
  UsersCreate:
    handler: bin/users/create
    events:
      - http:
          path: users
          method: post
          cors: true
  UsersUpdate:
    handler: bin/users/update
    events:
      - http:
          path: users
          method: put
          cors: true
  UsersRead:
    handler: bin/users/read
    events:
      - http:
          path: users/{id}
          method: get
          cors: true
  UsersDelete:
    handler: bin/users/delete
    events:
      - http:
          path: users/{id}
          method: delete
          cors: true

resources:
  - ${file(resources/dynamodb.yml)}
  - ${file(resources/cognito.yml)}
