service: paloma
app: paloma
tenant: drpappa
# org: DungBeetleBASH

# Serverless version
# Check out our docs for more details
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  region: eu-west-1
  profile: serverless-agent
  environment:
    USERS_TABLE: "PalomaUsers${self:provider.stage}"
  stackTags:
    app: paloma
  vpc:
    securityGroupIds:
      - sg-102ac57f
    subnetIds:
      - subnet-49e77422
      - subnet-48e77423
      - subnet-4fe77424
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [UsersTable, Arn]
    - Effect: Allow
      Action:
        - neptune-db:*
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:rds:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":cluster:"
            - Ref: PalomaDBCluster

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  - ${file(sls/functions/users.yml)}

resources:
  #- ${file(sls/resources/vpc.yml)}
  #- ${file(sls/resources/security.yml)}
  - ${file(sls/resources/neptune.yml)}
  - ${file(sls/resources/dynamodb.yml)}
  - ${file(sls/resources/cognito.yml)}
