service: paloma
app: paloma
# org: DungBeetleBASH

# Serverless version
# Check out our docs for more details
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  region: eu-west-1
  profile: serverless-agent
  environment:
    USERS_TABLE: "PalomaUsers${self:provider.stage}"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [UsersTable, Arn]
    - Effect: Allow
      Action:
        - neptune-db:*
      Resource:
        - "Fn::GetAtt": [PalomaDBCluster, Arn]

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  - ${file(sls/functions/users.yml)}

resources:
  # - ${file(sls/resources/neptune.yml)}
  - ${file(sls/resources/dynamodb.yml)}
  - ${file(sls/resources/cognito.yml)}
